version: "3"
services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling
    tty: true
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
      - bundle_data:/usr/local/bundle
    environment:
      JEKYLL_ENV: development

volumes:
  bundle_data:
